(function(g){var window=this;var PHa=function(a,b){return g.Mb(a,b)},m4=function(a,b,c){a.l.set(b,c)},n4=function(a){m4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ta()).toString(36));
return a},o4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Sm(a.l,b,c)},QHa=function(a,b){var c=[];
g.Xi(b,function(d){try{var e=g.Fn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.En(e)&&c.push(d)},a);
return c},RHa=function(a,b){var c=QHa(a,b);
g.Ab(c,function(d){g.Fn.prototype.remove.call(this,d)},a)},SHa=function(a){if(a.W){if(a.W.locationOverrideToken)return{locationOverrideToken:a.W.locationOverrideToken};
if(null!=a.W.latitudeE7&&null!=a.W.longitudeE7)return{latitudeE7:a.W.latitudeE7,longitudeE7:a.W.longitudeE7}}return null},THa=function(a,b){g.fb(a,b)||a.push(b)},p4=function(a){var b=0,c;
for(c in a)b++;return b},UHa=function(a,b){var c=b instanceof g.Gc?b:g.Mc(b,/^data:image\//i.test(b));
a.src=g.Hc(c)},VHa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},WHa=function(a){if(a.rg&&"function"==typeof a.rg)return a.rg();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},XHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)g.Ab(a,b,void 0);else{if(a.rh&&"function"==typeof a.rh)var c=a.rh();else if(a.rg&&"function"==typeof a.rg)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=WHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},YHa=function(a,b,c,d){var e=new g.Gm(null,void 0);
a&&g.Hm(e,a);b&&g.Im(e,b);c&&g.Jm(e,c);d&&(e.J=d);return e},q4=function(){},r4=function(a,b){g.vo[a]=!0;
var c=g.to();c&&c.publish.apply(c,arguments);g.vo[a]=!1},s4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Dm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ZHa(this,a.capabilities||""),$Ha(this,a.experiments||""))},ZHa=function(a,b){a.capabilities.clear();
g.Ne(b.split(","),g.Ra(PHa,aIa)).forEach(function(c){a.capabilities.add(c)})},$Ha=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},t4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},u4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},bIa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},cIa=function(a){return new t4(a)},dIa=function(a){return Array.isArray(a)?g.Qc(a,cIa):[]},v4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},w4=function(a){return Array.isArray(a)?"["+g.Qc(a,v4).join(",")+"]":"null"},x4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},eIa=function(a){return g.Qc(a,function(b){return{key:b.id,
name:b.name}})},y4=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},z4=function(a,b){return g.cb(a,function(c){return u4(c,b)})},fIa=function(){var a=(0,g.Eu)();
a&&RHa(a,a.i.Mj(!0))},A4=function(){var a=g.Hu("yt-remote-connected-devices")||[];
g.xb(a);return a},gIa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Qc(a,function(d,e){return 0==e?d:d.substring(c.length)})},hIa=function(a){g.Gu("yt-remote-connected-devices",a,86400)},C4=function(){if(B4)return B4;
var a=g.Hu("yt-remote-device-id");a||(a=x4(),g.Gu("yt-remote-device-id",a,31536E3));for(var b=A4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return B4=d},D4=function(){var a=A4(),b=C4();
g.fb(a,b);g.Ju()&&g.zb(a,b);a=gIa(a);if(g.gb(a))try{g.Mq("remote_sid")}catch(c){}else try{g.Kq("remote_sid",a.join(","),-1)}catch(c){}},iIa=function(){return g.Hu("yt-remote-session-browser-channel")},jIa=function(){return g.Hu("yt-remote-local-screens")||[]},kIa=function(){g.Gu("yt-remote-lounge-token-expiration",!0,86400)},lIa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Qc(jIa(),function(d){return d.loungeToken}),c=g.Qc(a,function(d){return d.loungeToken});
g.ah(c,function(d){return!g.fb(b,d)})&&kIa();
g.Gu("yt-remote-local-screens",a,31536E3)},mIa=function(a,b){g.Gu("yt-remote-session-browser-channel",a);
g.Gu("yt-remote-session-screen-id",b);var c=A4(),d=C4();g.fb(c,d)||c.push(d);hIa(c);D4()},E4=function(a){a||(g.Iu("yt-remote-session-screen-id"),g.Iu("yt-remote-session-video-id"));
D4();a=A4();g.kb(a,C4());hIa(a)},nIa=function(){if(!F4){var a=g.Pn();
a&&(F4=new g.zn(a))}},oIa=function(){nIa();
return F4?!!F4.get("yt-remote-use-staging-server"):!1},G4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},pIa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},qIa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},H4=function(a){a.length?rIa(a.shift(),function(){H4(a)}):I4()},sIa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},rIa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.nd(d,g.fg(a));(document.head||document.documentElement).appendChild(d)},tIa=function(){var a=G4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},I4=function(){var a=qIa();
a&&a(!1,"No cast extension found")},J4=function(){if(uIa){var a=2,b=qIa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;rIa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",I4,c)}},vIa=function(){J4();
var a=tIa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");H4(a)},xIa=function(){J4();
var a=tIa();a.push.apply(a,g.ma(wIa.map(sIa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");H4(a)},K4=function(a,b,c){g.E.call(this);
this.I=null!=c?(0,g.C)(a,c):a;this.Jf=b;this.C=(0,g.C)(this.NJ,this);this.i=!1;this.l=0;this.u=this.gb=null;this.B=[]},L4=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Jf=b;this.u=null;this.i=!1;this.l=0;this.gb=null},M4=function(a){a.gb=g.Bm(function(){a.gb=null;
a.i&&!a.l&&(a.i=!1,M4(a))},a.Jf);
var b=a.u;a.u=null;a.B.apply(null,b)},N4=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return VHa(a)},O4=function(){},P4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},R4=function(a){Q4.dispatchEvent(new yIa(Q4,a))},yIa=function(a,b){g.xl.call(this,"statevent",a);
this.stat=b},S4=function(){},zIa=function(){},BIa=function(a){return(a=AIa(a))?new ActiveXObject(a):new XMLHttpRequest},AIa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},T4=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.E_(this);this.u=new g.Am;this.u.setInterval(250)},DIa=function(a,b,c){a.Ap=1;
a.Rk=n4(b.clone());a.Bn=c;a.I=!0;CIa(a,null)},U4=function(a,b,c,d,e){a.Ap=1;
a.Rk=n4(b.clone());a.Bn=null;a.I=c;e&&(a.QG=!1);CIa(a,d)},CIa=function(a,b){a.mp=Date.now();
V4(a);a.Pl=a.Rk.clone();o4(a.Pl,"t",a.J);a.Es=0;a.De=a.i.Ax(a.i.ds()?b:null);0<a.xw&&(a.Ru=new L4((0,g.C)(a.LH,a,a.De),a.xw));a.B.ya(a.De,"readystatechange",a.ZP);var c=a.im?g.Vb(a.im):{};a.Bn?(a.Fv="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.De.send(a.Pl,a.Fv,a.Bn,c)):(a.Fv="GET",a.QG&&!g.De&&(c.Connection="close"),a.De.send(a.Pl,a.Fv,null,c));a.i.gi(1)},GIa=function(a,b,c){for(var d=!0;!a.Lm&&a.Es<c.length;){var e=EIa(a,c);
if(e==W4){4==b&&(a.Lk=4,R4(15),d=!1);break}else if(e==FIa){a.Lk=4;R4(16);d=!1;break}else X4(a,e)}4==b&&0==c.length&&(a.Lk=1,R4(17),d=!1);a.zi=a.zi&&d;d||(Y4(a),Z4(a))},EIa=function(a,b){var c=a.Es,d=b.indexOf("\n",c);
if(-1==d)return W4;c=Number(b.substring(c,d));if(isNaN(c))return FIa;d+=1;if(d+c>b.length)return W4;var e=b.substr(d,c);a.Es=d+c;return e},IIa=function(a,b){a.mp=Date.now();
V4(a);var c=b?window.location.hostname:"";a.Pl=a.Rk.clone();m4(a.Pl,"DOMAIN",c);m4(a.Pl,"t",a.J);try{a.Di=new ActiveXObject("htmlfile")}catch(n){Y4(a);a.Lk=7;R4(22);Z4(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in $4)h=$4[h];else if(h in HIa)h=$4[h]=HIa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
$4[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.hc("b/12014412"),d+"</body></html>");a.Di.open();a.Di.write(g.gd(c));a.Di.close();a.Di.parentWindow.m=(0,g.C)(a.vP,a);a.Di.parentWindow.d=(0,g.C)(a.bG,a,!0);a.Di.parentWindow.rpcClose=(0,g.C)(a.bG,a,!1);c=a.Di.createElement("DIV");a.Di.parentWindow.document.body.appendChild(c);d=g.Lc(a.Pl.toString());d=g.sd(g.Hc(d));d=g.kd(g.hc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ld(c,d);a.i.gi(1)},V4=function(a){a.NA=Date.now()+
a.C;
JIa(a,a.C)},JIa=function(a,b){if(null!=a.Gp)throw Error("WatchDog timer not null");
a.Gp=P4((0,g.C)(a.DP,a),b)},a5=function(a){a.Gp&&(g.A.clearTimeout(a.Gp),a.Gp=null)},Z4=function(a){a.i.KB()||a.Lm||a.i.Ts(a)},Y4=function(a){a5(a);
g.zi(a.Ru);a.Ru=null;a.u.stop();g.HCa(a.B);if(a.De){var b=a.De;a.De=null;b.abort();b.dispose()}a.Di&&(a.Di=null)},X4=function(a,b){try{a.i.SF(a,b),a.i.gi(4)}catch(c){}},LIa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;KIa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){LIa(a,b,c,d,f)},f)})}},KIa=function(a,b,c){var d=new Image;
d.onload=function(){try{b5(d),c(!0)}catch(e){}};
d.onerror=function(){try{b5(d),c(!1)}catch(e){}};
d.onabort=function(){try{b5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{b5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
UHa(d,a)},b5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},c5=function(a){g.Rl.call(this);
this.headers=new g.Dm;this.ea=a||null;this.B=!1;this.ca=this.i=null;this.za=this.W="";this.I=0;this.u="";this.C=this.la=this.L=this.ga=!1;this.J=0;this.X=null;this.Da="";this.Y=this.ia=!1},MIa=function(a){return g.Be&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},NIa=function(a){return"content-type"==a.toLowerCase()},PIa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.I=5;OIa(a);d5(a)},OIa=function(a){a.ga||(a.ga=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},RIa=function(a){if(a.B&&"undefined"!=typeof g.H_)if(a.ca[1]&&4==e5(a)&&2==a.getStatus())f5(a,"Local request error detected and ignored");
else if(a.L&&4==e5(a))g.Bm(a.PF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){f5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Bd(1,String(a.W));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!QIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<e5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";OIa(a)}}finally{d5(a)}}},d5=function(a,b){if(a.i){SIa(a);
var c=a.i,d=a.ca[0]?g.Ka:null;a.i=null;a.ca=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},SIa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},e5=function(a){return a.i?a.i.readyState:0},g5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},f5=function(a,b){return b+" ["+a.za+" "+a.W+" "+a.getStatus()+"]"},TIa=function(a){this.i=a;
this.l=new O4},UIa=function(a){var b=h5(a.i,a.mq,"/mail/images/cleardot.gif");
n4(b);LIa(b.toString(),5E3,(0,g.C)(a.DK,a),3,2E3);a.gi(1)},j5=function(a){var b=a.i.L;
if(null!=b)R4(5),b?(R4(11),i5(a.i,a,!1)):(R4(12),i5(a.i,a,!0));else if(a.Bg=new T4(a,void 0,void 0,void 0),a.Bg.im=a.yw,b=a.i,b=h5(b,b.ds()?a.cq:null,a.zw),R4(5),!g.Be||g.de(10))o4(b,"TYPE","xmlhttp"),U4(a.Bg,b,!1,a.cq,!1);else{o4(b,"TYPE","html");var c=a.Bg;a=!!a.cq;c.Ap=3;c.Rk=n4(b.clone());IIa(c,a)}},k5=function(a,b,c){this.Ma=1;
this.i=[];this.u=[];this.B=new O4;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},VIa=function(a,b){this.i=a;
this.map=b;this.context=null},WIa=function(a,b,c,d){g.xl.call(this,"timingevent",a);
this.size=b;this.Tr=d},XIa=function(a){g.xl.call(this,"serverreachability",a)},$Ia=function(a){YIa(a);
if(3==a.Ma){var b=a.yr++,c=a.At.clone();m4(c,"SID",a.l);m4(c,"RID",b);m4(c,"TYPE","terminate");l5(a,c);b=new T4(a,a.l,b,void 0);b.Ap=2;b.Rk=n4(c.clone());UHa(new Image,b.Rk.toString());b.mp=Date.now();V4(b)}ZIa(a)},aJa=function(a){a.XK(1,0);
a.At=h5(a,null,a.Aw);m5(a)},YIa=function(a){a.Vk&&(a.Vk.abort(),a.Vk=null);
a.Xd&&(a.Xd.cancel(),a.Xd=null);a.Oj&&(g.A.clearTimeout(a.Oj),a.Oj=null);n5(a);a.og&&(a.og.cancel(),a.og=null);a.il&&(g.A.clearTimeout(a.il),a.il=null)},bJa=function(a,b){if(0==a.Ma)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new VIa(a.tM++,b));2!=a.Ma&&3!=a.Ma||m5(a)},cJa=function(a){var b=0;
a.Xd&&b++;a.og&&b++;return b},m5=function(a){a.og||a.il||(a.il=P4((0,g.C)(a.ZF,a),0),a.wo=0)},eJa=function(a,b){if(1==a.Ma){if(!b){a.yr=Math.floor(1E5*Math.random());
var c=a.yr++,d=new T4(a,"",c,void 0);d.im=a.Ji;var e=o5(a),f=a.At.clone();m4(f,"RID",c);m4(f,"CVER","1");l5(a,f);DIa(d,f,e);a.og=d;a.Ma=2}}else 3==a.Ma&&(b?dJa(a,b):0==a.i.length||a.og||dJa(a))},dJa=function(a,b){if(b)if(6<a.Mm){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.yr-1;var d=o5(a)}else c=b.L,d=b.Bn;else c=a.yr++,d=o5(a);var e=a.At.clone();m4(e,"SID",a.l);m4(e,"RID",c);m4(e,"AID",a.Qo);l5(a,e);c=new T4(a,a.l,c,a.wo+1);c.im=a.Ji;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.og=c;DIa(c,e,d)},l5=function(a,b){if(a.Bf){var c=a.Bf.vD();
c&&g.Cb(c,function(d,e){m4(b,e,d)})}},o5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Mm&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Rn:e.Rn},f++){e.Rn=a.i[f].i;var h=a.i[f].map;e.Rn=6>=a.Mm?f:e.Rn-d;try{g.Cb(h,function(l){return function(m,n){c.push("req"+l.Rn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Rn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},fJa=function(a){a.Xd||a.Oj||(a.I=1,a.Oj=P4((0,g.C)(a.YF,a),0),a.fo=0)},p5=function(a){if(a.Xd||a.Oj||3<=a.fo)return!1;
a.I++;a.Oj=P4((0,g.C)(a.YF,a),gJa(a,a.fo));a.fo++;return!0},i5=function(a,b,c){a.Dv=c;
a.Ki=b.Kj;a.C||aJa(a)},n5=function(a){null!=a.Um&&(g.A.clearTimeout(a.Um),a.Um=null)},gJa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},q5=function(a,b){if(2==b||9==b){var c=null;
a.Bf&&(c=null);var d=(0,g.C)(a.GQ,a);c||(c=new g.Gm("//www.google.com/images/cleardot.gif"),n4(c));KIa(c.toString(),1E4,d)}else R4(2);hJa(a,b)},hJa=function(a,b){a.Ma=0;
a.Bf&&a.Bf.KC(b);ZIa(a);YIa(a)},ZIa=function(a){a.Ma=0;
a.Ki=-1;if(a.Bf)if(0==a.u.length&&0==a.i.length)a.Bf.jx();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.Bf.jx(b)}},h5=function(a,b,c){var d=g.Om(c);
if(""!=d.i)b&&g.Im(d,b+"."+d.i),g.Jm(d,d.u);else{var e=window.location;d=YHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Fq&&g.Cb(a.Fq,function(f,h){m4(d,h,f)});
m4(d,"VER",a.Mm);l5(a,d);return d},iJa=function(){},jJa=function(){this.i=[];
this.l=[]},kJa=function(a,b){this.action=a;
this.params=b||{}},r5=function(a,b){g.E.call(this);
this.i=new g.J(this.nP,0,this);g.I(this,this.i);this.Jf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},s5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ca=a;this.I=b;this.u=new g.yn;this.l=new r5(this.jQ,this);this.i=null;this.X=!1;this.C=null;this.W="";this.L=this.B=0;this.J=[];this.ea=c;this.Y=d;this.ia=e},lJa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Dv,sessionId:a.i.l,arrayId:a.i.Qo}},mJa=function(a,b){a.L=b||0;
a.l.stop();t5(a);a.i&&(3==a.i.getState()&&eJa(a.i),$Ia(a.i));a.L=0},u5=function(a){return!!a.i&&3==a.i.getState()},t5=function(a){if(a.i){var b=a.Y(),c=a.i.Ji||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ji=c}},v5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.Bd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Cd(a)||"";a=g.Wc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ec(a,"10.0")&&(this.l=!1))},w5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Od(c+b,{})},x5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.B,d,!0),onError:g.Ra(a.u,e),onTimeout:g.Ra(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Pp(b,a)},qJa=function(){var a=nJa;
oJa();y5.push(a);pJa()},z5=function(a,b){oJa();
var c=rJa(a,String(b));g.gb(y5)?sJa(c):(pJa(),g.Ab(y5,function(d){d(c)}))},oJa=function(){y5||(y5=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",y5,void 0))},sJa=function(a){var b=(A5+1)%50;
A5=b;B5[b]=a;C5||(C5=49==b)},pJa=function(){var a=y5;
if(B5[0]){var b=C5?A5:-1;do{b=(b+1)%50;var c=B5[b];g.Ab(a,function(d){d(c)})}while(b!=A5);
B5=Array(50);A5=-1;C5=!1}},rJa=function(a,b){var c=(Date.now()-tJa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},D5=function(a){g.R.call(this);
this.I=a;this.screens=[]},uJa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},vJa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ne(a.screens,function(f){return!!y4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=uJa(a,b[d])||c;return c},wJa=function(a,b){var c=a.screens.length;
a.screens=g.Ne(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},E5=function(a,b,c,d,e){g.R.call(this);
this.u=a;this.J=b;this.B=c;this.I=d;this.C=e;this.l=0;this.i=null;this.gb=NaN},G5=function(a){D5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;F5(this);this.info("Initializing with "+w4(this.screens))},xJa=function(a){if(a.screens.length){var b=g.Qc(a.screens,function(d){return d.id}),c=w5(a.l,"/pairing/get_lounge_token_batch");
x5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.wL,a),(0,g.C)(a.vL,a))}},F5=function(a){if(g.Go("deprecate_pair_servlet_enabled"))return vJa(a,[]);
var b=dIa(jIa());b=g.Ne(b,function(c){return!c.uuid});
return vJa(a,b)},H5=function(a,b){lIa(g.Qc(a.screens,bIa));
b&&kIa()},J5=function(a,b){g.R.call(this);
this.I=b;var c=g.Hu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;I5("Initialized with "+g.yj(this.i))},K5=function(a,b,c){var d=w5(a.C,"/pairing/get_screen_availability");
x5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},L5=function(a,b){a:if(p4(b)!=p4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(I5("Updated online screens: "+g.yj(a.i)),a.i=b,a.V("screenChange"));yJa(a)},M5=function(a){isNaN(a.u)||g.so(a.u);
a.u=g.qo((0,g.C)(a.Nz,a),0<a.B&&a.B<g.Ta()?2E4:1E4)},I5=function(a){z5("OnlineScreenService",a)},zJa=function(a){var b={};
g.Ab(a.I(),function(c){c.token?b[c.token]=c.id:this.Gd("Requesting availability of screen w/o lounge token.")});
return b},yJa=function(a){a=g.Kb(g.Db(a.i,function(b){return b}));
g.xb(a);a.length?g.Gu("yt-remote-online-screen-ids",a.join(","),60):g.Iu("yt-remote-online-screen-ids")},N5=function(a){D5.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};AJa(this)},CJa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Kg();if(h=(c?z4(h,c):null)||z4(h,b)){h.uuid=b;var l=O5(a,h);K5(a.i,l,function(m){e(m?l:null)})}else c?BJa(a,c,(0,g.C)(function(m){var n=O5(this,new t4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));K5(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},DJa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},EJa=function(a,b,c){K5(a.i,b,c)},BJa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Pp(w5(a.B,"/pairing/get_lounge_token_batch"),e)},FJa=function(a){a.screens=a.l.Kg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+w4(a.screens))},AJa=function(a){P5(a);
a.l=new G5(a.B);a.l.subscribe("screenChange",(0,g.C)(a.CL,a));FJa(a);a.u=dIa(g.Hu("yt-remote-automatic-screen-cache")||[]);P5(a);a.info("Initializing automatic screens: "+w4(a.u));a.i=new J5(a.B,(0,g.C)(a.Kg,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.V("onlineScreenChange")},a))},O5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=z4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),GJa(a));P5(a);a.C[b.uuid]=b.id;g.Gu("yt-remote-device-id-map",a.C,31536E3);return b},GJa=function(a){a=g.Ne(a.u,function(b){return"shortLived"!=b.idType});
g.Gu("yt-remote-automatic-screen-cache",g.Qc(a,bIa))},P5=function(a){a.C=g.Hu("yt-remote-device-id-map")||{}},Q5=function(a,b,c){g.R.call(this);
this.ia=c;this.u=a;this.i=b;this.B=null},R5=function(a,b){a.B=b;
a.V("sessionScreen",a.B)},HJa=function(a,b){a.B&&(a.B.token=b,O5(a.u,a.B));
a.V("sessionScreen",a.B)},S5=function(a,b){z5(a.ia,b)},T5=function(a,b,c){Q5.call(this,a,b,"CastSession");
var d=this;this.ga=c;this.l=null;this.Y=(0,g.C)(this.SJ,this);this.ea=(0,g.C)(this.HP,this);this.X=g.qo(function(){IJa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.ca=!1;this.W="unknown"},U5=function(a,b){g.so(a.J);
a.J=0;0==b?JJa(a):a.J=g.qo(function(){JJa(a)},b)},JJa=function(a){KJa(a,"getLoungeToken");
g.so(a.C);a.C=g.qo(function(){LJa(a,null)},3E4)},KJa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.yj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ka,(0,g.C)(function(){S5(this,"Failed to send message: "+b+".")},a)):S5(a,"Sending yt message without session: "+g.yj(c))},V5=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.KD(b,function(c){R5(a,c)},function(){return a.cg()},5)):a.cg(Error("Waiting for session status timed out."))},NJa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new t4(b);MJa(a,d,function(e){e?(a.ca=!0,O5(a.u,d),R5(a,d),a.W="unknown",U5(a,c)):(g.no(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.cg())},5)},IJa=function(a,b){g.so(a.X);
a.X=0;b?a.ga.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?NJa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.no(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),V5(a,b.screenId))):(g.no(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
V5(a,b.screenId)):V5(a,b.screenId):a.cg(Error("Waiting for session status timed out."))},LJa=function(a,b){g.so(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.W=c,U5(a,3E4)):(HJa(a,b.loungeToken),a.ca=!1,a.W="unknown",U5(a,b.loungeTokenRefreshIntervalMs))},MJa=function(a,b,c,d){g.so(a.I);
a.I=0;EJa(a.u,b,function(e){e||0>d?c(e):a.I=g.qo(function(){MJa(a,b,c,d-1)},300)})},OJa=function(a){g.so(a.L);
a.L=0;g.so(a.I);a.I=0;g.so(a.X);a.X=0;g.so(a.C);a.C=0;g.so(a.J);a.J=0},W5=function(a,b,c,d){Q5.call(this,a,b,"DialSession");
this.ma=d;this.l=this.L=null;this.ea="";this.za=c;this.la=null;this.X=g.Ka;this.W=NaN;this.ga=(0,g.C)(this.TJ,this);this.C=g.Ka;this.J=this.I=0;this.Y=!1;this.ca="unknown"},X5=function(a){var b;
return!!(a.ma.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},PJa=function(a){a.C=a.u.MB(a.ea,a.i.label,a.i.friendlyName,X5(a),function(b,c){a.C=g.Ka;
a.Y=!0;R5(a,b);"shortLived"==b.idType&&0<c&&Y5(a,c)},function(b){a.C=g.Ka;
a.cg(b)})},QJa=function(a){var b={};
b.pairingCode=a.ea;b.theme=a.za;oIa()&&(b.env_useStageMdx=1);return g.Md(b)},Z5=function(a){return new Promise(function(b){a.ea=x4();
if(a.la){var c=new chrome.cast.DialLaunchResponse(!0,QJa(a));b(c);PJa(a)}else a.X=function(){g.so(a.W);a.X=function(){};
a.W=NaN;var d=new chrome.cast.DialLaunchResponse(!0,QJa(a));b(d);PJa(a)},a.W=g.qo(function(){a.X()},100)})},SJa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new t4(b);return(new Promise(function(e){RJa(a,d,function(f){f?(a.Y=!0,O5(a.u,d),R5(a,d),Y5(a,c)):g.no(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):Z5(a)})},TJa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){CJa(a.u,c,b,d,function(f){f&&f.token&&R5(a,f);e(f)},function(f){S5(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):Z5(a)})},RJa=function(a,b,c,d){g.so(a.I);
a.I=0;EJa(a.u,b,function(e){e||0>d?c(e):a.I=g.qo(function(){RJa(a,b,c,d-1)},300)})},Y5=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
X5(a)&&(g.so(a.J),a.J=0,0==b?UJa(a):a.J=g.qo(function(){UJa(a)},b))},UJa=function(a){X5(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ca=c,Y5(a,3E4)):(a.Y=!1,a.ca="unknown",HJa(a,b.loungeToken),Y5(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ca="noLoungeTokenResponse";Y5(a,3E4)})},VJa=function(a){g.so(a.I);
a.I=0;g.so(a.J);a.J=0;a.C();a.C=function(){};
g.so(a.W)},$5=function(a,b){Q5.call(this,a,b,"ManualSession");
this.l=g.qo((0,g.C)(this.Ro,this,null),150)},a6=function(a,b){g.R.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.W=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.I=(0,g.C)(this.DO,this)},WJa=function(a,b){return b?g.cb(a.u,function(c){return u4(b,c.label)},a):null},b6=function(a){z5("Controller",a)},nJa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},c6=function(a){return a.J||!!a.u.length||!!a.i},d6=function(a,b,c){b!=a.i&&(g.zi(a.i),(a.i=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.i):a.V("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.WF,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Ro(null)):a.V("yt-remote-cast2-session-change",null))},XJa=function(a){var b=a.l.LB(),c=a.i&&a.i.i;
a=g.Qc(b,function(d){c&&u4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=WJa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bKa=function(a,b,c,d){d.disableCastApi?e6("Cannot initialize because disabled by Mdx config."):YJa()?ZJa(b,d)&&(f6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?$Ja(a,c):(window.__onGCastApiAvailable=function(e,f){e?$Ja(a,c):(g6("Failed to load cast API: "+f),h6(!1),f6(!1),g.Iu("yt-remote-cast-available"),g.Iu("yt-remote-cast-receiver"),
aKa(),c(!1))},d.loadCastApiSetupScript?g.Co("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=G4()&&vIa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?I4():89<=G4()?xIa():(J4(),H4(wIa.map(sIa))))):e6("Cannot initialize because not running Chrome")},aKa=function(){e6("dispose");
var a=i6();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);cKa(!1);g.yo(j6);j6.length=0},k6=function(){return!!g.Hu("yt-remote-cast-installed")},dKa=function(){var a=g.Hu("yt-remote-cast-receiver");
return a?a.friendlyName:null},eKa=function(){e6("clearCurrentReceiver");
g.Iu("yt-remote-cast-receiver")},fKa=function(){return k6()?i6()?i6().getCastSession():(g6("getCastSelector: Cast is not initialized."),null):(g6("getCastSelector: Cast API is not installed!"),null)},m6=function(){k6()?i6()?l6()?(e6("Requesting cast selector."),i6().requestSession()):(e6("Wait for cast API to be ready to request the session."),j6.push(g.xo("yt-remote-cast2-api-ready",m6))):g6("requestCastSelector: Cast is not initialized."):g6("requestCastSelector: Cast API is not installed!")},n6=
function(a,b){l6()?i6().setConnectedScreenStatus(a,b):g6("setConnectedScreenStatus called before ready.")},YJa=function(){var a=0<=g.Wc.search(/ (CrMo|Chrome|CriOS)\//);
return g.FA||a},gKa=function(a,b){i6().init(a,b)},ZJa=function(a,b){var c=!1;
i6()||(c=new a6(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Gu("yt-remote-cast-available",d);r4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){e6("onReceiverSelected: "+d.friendlyName);
g.Gu("yt-remote-cast-receiver",d);r4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){e6("onReceiverResumed: "+d.friendlyName);
g.Gu("yt-remote-cast-receiver",d);r4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){e6("onSessionChange: "+v4(d));
d||g.Iu("yt-remote-cast-receiver");r4("yt-remote-cast2-session-change",d)}),g.Ea("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
e6("cloudview.createSingleton_: "+c);return c},i6=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},$Ja=function(a,b){h6(!0);
f6(!1);gKa(a,function(c){c?(cKa(!0),g.zo("yt-remote-cast2-api-ready")):(g6("Failed to initialize cast API."),h6(!1),g.Iu("yt-remote-cast-available"),g.Iu("yt-remote-cast-receiver"),aKa());b(c)})},e6=function(a){z5("cloudview",a)},g6=function(a){z5("cloudview",a)},h6=function(a){e6("setCastInstalled_ "+a);
g.Gu("yt-remote-cast-installed",a)},l6=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},cKa=function(a){e6("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},f6=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},o6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.L=0;this.i=null;this.hasNext=this.aj=!1;this.W=this.I=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},p6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.aj=!1;a.hasNext=!1;a.L=0;a.J=g.Ta();a.C=0;a.l=0;a.I=0;a.W=0;a.B=NaN;a.u=!1},q6=function(a){return a.Nb()?(g.Ta()-a.J)/1E3:0},r6=function(a,b){a.L=b;
a.J=g.Ta()},s6=function(a){switch(a.playerState){case 1:case 1081:return(g.Ta()-a.J)/1E3+a.L;
case -1E3:return 0}return a.L},t6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&p6(a)},u6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.i);b.hasPrevious=a.aj;b.hasNext=a.hasNext;b.playerTime=a.L;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.I;b.loadedTime=a.W;b.liveIngestionTime=a.B;return b},w6=function(a,b){g.R.call(this);
this.Ma=0;this.u=a;this.C=[];this.B=new jJa;this.l=this.i=null;this.L=(0,g.C)(this.eN,this);this.I=(0,g.C)(this.Cr,this);this.J=(0,g.C)(this.dN,this);this.W=(0,g.C)(this.lN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.bA,this),hKa(this))):c=3;0!=c&&(b?this.bA(c):g.qo((0,g.C)(function(){this.bA(c)},this),0));
var d=fKa();d&&v6(this,d);this.subscribe("yt-remote-cast2-session-change",this.W)},x6=function(a){return new o6(a.u.getPlayerContextData())},hKa=function(a){g.Ab("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Ra(this.AO,b),this))},a)},iKa=function(a){g.Ab(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},y6=function(a){return 1==a.getState()},z6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},B6=function(a,b,c){var d=x6(a);
r6(d,c);-1E3!=d.playerState&&(d.playerState=b);A6(a,d)},C6=function(a,b,c){a.u.sendMessage(b,c)},A6=function(a,b){iKa(a);
a.u.setPlayerContextData(u6(b));hKa(a)},v6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.Cr(null));
a.l=b;a.l&&(z5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.Cr(a.l.media[0]))},jKa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=x6(a);b.contentId!=d.videoId&&z5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;r6(d,a.i.getEstimatedTime());A6(a,d)}else z5("CP","No cast media video. Ignoring state update.")},D6=function(a,b,c){return(0,g.C)(function(d){this.Gd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gd("Retrying "+b+" using MDx browser channel."),C6(this,b,c))},a)},E6=function(a,b,c){g.R.call(this);
this.C=NaN;this.ca=!1;this.L=this.J=this.X=this.Y=NaN;this.W=[];this.B=this.I=this.u=this.Hb=this.i=null;this.ia=a;this.W.push(g.So(window,"beforeunload",(0,g.C)(this.qL,this)));this.l=[];this.Hb=new o6;this.ga=b.id;this.ea=b.idType;this.i=kKa(this,c);this.i.subscribe("handlerOpened",this.iN,this);this.i.subscribe("handlerClosed",this.fN,this);this.i.subscribe("handlerError",this.gN,this);this.i.subscribe("handlerMessage",this.hN,this);this.i.cv(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Hb.videoId;g.Ju()&&g.Gu("yt-remote-session-video-id",d)},this)},F6=function(a){z5("conn",a)},kKa=function(a,b){return new s5(w5(a.ia,"/bc"),b,!1,function(){return a.QB()},"shortLived"==a.ea)},G6=function(a,b){a.V("proxyStateChange",b)},lKa=function(a){a.C=g.qo((0,g.C)(function(){F6("Connecting timeout");
this.qo(1)},a),2E4)},H6=function(a){g.so(a.C);
a.C=NaN},I6=function(a){g.so(a.Y);
a.Y=NaN},mKa=function(a){J6(a);
a.X=g.qo((0,g.C)(function(){K6(this,"getNowPlaying")},a),2E4)},J6=function(a){g.so(a.X);
a.X=NaN},oKa=function(a,b){b&&(H6(a),I6(a));
var c=u5(a.i)&&isNaN(a.C);b==c?b&&(G6(a,1),K6(a,"getSubtitlesTrack")):b?(a.JD()&&a.Hb.reset(),G6(a,1),K6(a,"getNowPlaying"),nKa(a)):a.qo(1)},pKa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Hb.videoId&&(g.Pb(b.params)?a.Hb.i=null:a.Hb.i=b.params,a.V("remotePlayerChange"))},qKa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Hb.listId=b.params.listId||a.Hb.listId;t6(a.Hb,c,d);a.V("remoteQueueChange")},sKa=function(a,b){b.params=b.params||{};
qKa(a,b);rKa(a,b);a.V("autoplayDismissed")},rKa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
r6(a.Hb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Hb.playerState&&(c=-1E3);a.Hb.playerState=c;c=Number(b.params.loadedTime);a.Hb.W=isNaN(c)?0:c;c=Number(b.params.duration);a.Hb.I=isNaN(c)?0:c;c=a.Hb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Hb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Hb.playerState?mKa(a):J6(a);a.V("remotePlayerChange")},tKa=function(a,b){if(-1E3!=
a.Hb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Hb.playerState=c;c=parseInt(b.params.currentTime,10);r6(a.Hb,isNaN(c)?0:c);a.V("remotePlayerChange")}},uKa=function(a,b){var c="true"==b.params.muted;
a.Hb.volume=parseInt(b.params.volume,10);a.Hb.muted=c;a.V("remotePlayerChange")},vKa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},wKa=function(a,b){var c="true"==b.params.hasNext;
a.Hb.aj="true"==b.params.hasPrevious;a.Hb.hasNext=c;a.V("previousNextChange")},nKa=function(a){g.so(a.L);
a.L=g.qo((0,g.C)(a.qo,a,1),864E5)},K6=function(a,b,c){c?F6("Sending: action="+b+", params="+g.yj(c)):F6("Sending: action="+b);
a.i.sendMessage(b,c)},L6=function(a){D5.call(this,"ScreenServiceProxy");
this.If=a;this.i=[];this.i.push(this.If.$_s("screenChange",(0,g.C)(this.XJ,this)));this.i.push(this.If.$_s("onlineScreenChange",(0,g.C)(this.hO,this)))},AKa=function(a,b){nIa();
if(!F4||!F4.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;fIa();D4();M6||(M6=new v5(b?b.loungeApiHost:void 0),oIa()&&(M6.i="/api/loungedev"));N6||(N6=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",N6,void 0));xKa();var c=O6();if(!c){var d=new N5(M6);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=O6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});bKa(a,d,function(h){h?P6()&&n6(P6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){r4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ja("yt.mdx.remote.initialized_")){g.Ea("yt.mdx.remote.initialized_",!0,void 0);
Q6("Initializing: "+g.yj(b));R6.push(g.xo("yt-remote-cast2-availability-change",function(){r4("yt-remote-receiver-availability-change")}));
R6.push(g.xo("yt-remote-cast2-receiver-selected",function(){S6(null);r4("yt-remote-auto-connect","cast-selector-receiver")}));
R6.push(g.xo("yt-remote-cast2-receiver-resumed",function(){r4("yt-remote-receiver-resumed","cast-selector-receiver")}));
R6.push(g.xo("yt-remote-cast2-session-change",yKa));R6.push(g.xo("yt-remote-connection-change",function(h){h?n6(P6(),"YouTube TV"):T6()||(n6(null,null),eKa())}));
e=U6();b.isAuto&&(e.id+="#dial");g.Go("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);Q6(" -- with channel params: "+g.yj(e));e?(g.Gu("yt-remote-session-app",e.app),g.Gu("yt-remote-session-name",e.name)):(g.Iu("yt-remote-session-app"),g.Iu("yt-remote-session-name"));g.Ea("yt.mdx.remote.channelParams_",e,void 0);c.start();P6()||zKa()}}},BKa=function(){var a=O6().If.$_gos();
var b=V6();b&&W6()&&(y4(a,b)||a.push(b));return eIa(a)},X6=function(){var a=CKa();
!a&&k6()&&dKa()&&(a={key:"cast-selector-receiver",name:dKa()});return a},CKa=function(){var a=BKa(),b=V6();
b||(b=T6());return g.cb(a,function(c){return b&&u4(b,c.key)?!0:!1})},V6=function(){var a=P6();
if(!a)return null;var b=O6().Kg();return z4(b,a)},yKa=function(a){Q6("remote.onCastSessionChange_: "+v4(a));
if(a){var b=V6();if(b&&b.id==a.id){if(n6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))Y6&&(Y6.token=a),(b=W6())&&b.cv(a)}else b&&Z6(),$6(a,1)}else W6()&&Z6()},Z6=function(){l6()?i6().stopSession():g6("stopSession called before API ready.");
var a=W6();a&&(a.disconnect(1),a7(null))},b7=function(){var a=W6();
return!!a&&3!=a.getProxyState()},Q6=function(a){z5("remote",a)},O6=function(){if(!c7){var a=g.Ja("yt.mdx.remote.screenService_");
c7=a?new L6(a):null}return c7},P6=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},DKa=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},EKa=function(){return g.Ja("yt.mdx.remote.connectData_")},S6=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},W6=function(){return g.Ja("yt.mdx.remote.connection_")},a7=function(a){var b=W6();
S6(null);a||DKa("");g.Ea("yt.mdx.remote.connection_",a,void 0);N6&&(g.Ab(N6,function(c){c(a)}),N6.length=0);
b&&!a?r4("yt-remote-connection-change",!1):!b&&a&&r4("yt-remote-connection-change",!0)},T6=function(){var a=g.Ju();
if(!a)return null;var b=O6();if(!b)return null;b=b.Kg();return z4(b,a)},$6=function(a,b){P6();
V6()&&V6();if(d7)Y6=a;else{DKa(a.id);var c=new E6(M6,a,U6());c.connect(b,EKa());c.subscribe("beforeDisconnect",function(d){r4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){W6()&&(W6(),a7(null))});
c.subscribe("browserChannelAuthError",function(){var d=V6();d&&"shortLived"==d.idType&&(l6()?i6().handleBrowserChannelAuthError():g6("refreshLoungeToken called before API ready."))});
a7(c)}},zKa=function(){var a=T6();
a?(Q6("Resume connection to: "+v4(a)),$6(a,0)):(E4(),eKa(),Q6("Skipping connecting because no session screen found."))},xKa=function(){var a=U6();
if(g.Pb(a)){a=C4();var b=g.Hu("yt-remote-session-name")||"",c=g.Hu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},U6=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},e7=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.G=b;this.xb=c;this.events=new g.$M(this);this.X=this.events.N(this.G,"onVolumeChange",function(e){FKa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.dK(64);this.i=new g.J(this.ZG,500,this);this.u=new g.J(this.aH,1E3,this);this.L=new K4(this.XQ,0,this);this.B={};this.W=new g.J(this.CH,1E3,this);this.J=new L4(this.seekTo,1E3,this);this.Y=g.Ka;g.I(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.QN);this.events.N(b,"captionschanged",this.bN);this.events.N(b,"captionssettingschanged",this.fH);this.events.N(b,"videoplayerreset",this.Lu);this.events.N(b,"mdxautoplaycancel",function(){d.xb.eD()});
a=this.xb;a.na();a.subscribe("proxyStateChange",this.RF,this);a.subscribe("remotePlayerChange",this.Ir,this);a.subscribe("remoteQueueChange",this.Lu,this);a.subscribe("previousNextChange",this.OF,this);a.subscribe("nowAutoplaying",this.IF,this);a.subscribe("autoplayDismissed",this.gF,this);g.I(this,this.i);g.I(this,this.u);g.I(this,this.L);g.I(this,this.W);g.I(this,this.J);this.fH();this.Lu();this.Ir()},FKa=function(a,b){if(f7(a)){a.xb.unsubscribe("remotePlayerChange",a.Ir,a);
var c=Math.round(b.volume),d=!!b.muted,e=x6(a.xb);if(c!==e.volume||d!==e.muted)a.xb.setVolume(c,d),a.W.start();a.xb.subscribe("remotePlayerChange",a.Ir,a)}},GKa=function(a){a.Db(0);
a.i.stop();a.tb(new g.dK(64))},g7=function(a,b){if(f7(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Yb(c,b));a.xb.PB(a.G.getVideoData(1).videoId,c);a.B=x6(a.xb).i}},h7=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.xb.playVideo(c.videoId,b,d,e,c.playerParams,c.ga,SHa(c));a.tb(new g.dK(1))},HKa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{cE:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},f7=function(a){return x6(a.xb).videoId===a.G.getVideoData(1).videoId},i7=function(){g.X.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ba:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ba:"Learn more"},{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],ba:"OK"}]}]}]});this.i=new g.NL(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.I(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},j7=function(){g.X.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ba:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",ba:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-privacy-popup-cancel"],ba:"Cancel"},{D:"button",ka:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ba:"Confirm"}]}]}]});this.i=new g.NL(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},k7=function(a){g.X.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.qma()]},{D:"div",K:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.api=a;this.i=new g.NL(this,250);g.I(this,this.i);this.N(a,"presentingplayerstatechange",this.l);IKa(this,a.Wa())},IKa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.CJ("Error on $RECEIVER_NAME",c):b.Nb()||g.W(b,4)?g.CJ("Playing on $RECEIVER_NAME",c):g.CJ("Connected to $RECEIVER_NAME",c);a.Aa("statustext",c);a.i.show()}else a.i.hide()},l7=function(a,b){g.SP.call(this,"Play on",0,a,b);
this.G=a;this.Ml={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},m7=function(a){g.hN.call(this,a);
this.ci={key:x4(),name:"This computer"};this.lh=null;this.subscriptions=[];this.Dz=this.xb=null;this.Ml=[this.ci];this.Xk=this.ci;this.Qc=new g.dK(64);this.xE=0;this.Ne=-1;this.Vo=null;this.Lr=this.pu=!1;this.An=this.kp=null;if(!g.ZF(this.player.T())){a=this.player;var b=g.NM(a);b&&(b=b.en())&&(b=new l7(a,b),g.I(this,b));b=new k7(a);g.I(this,b);g.XM(a,b.element,4);this.kp=new j7;g.I(this,this.kp);g.XM(a,this.kp.element,4);g.U(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.U(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Vo=new i7,g.I(this,this.Vo),g.XM(a,this.Vo.element,4));this.Lr=!!T6();this.pu=!!g.Hu("yt-remote-manual-pairing-warning-shown")}},n7=function(a){a.An&&(a.player.removeEventListener("presentingplayerstatechange",a.An),a.An=null)},JKa=function(a,b,c){a.Qc=c;
a.player.V("presentingplayerstatechange",new g.iJ(c,b))},KKa=function(a,b,c){var d=!1;
1===b?d=!a.Lr:2===b&&(d=!a.pu);d&&g.kJ(c,8)&&(a.player.pauseVideo(),n7(a))},o7=function(a,b){if(b.key!==a.Xk.key)if(b.key===a.ci.key)Z6();
else{if(a.Vo&&!a.pu&&b!==a.ci&&"cast-selector-receiver"!==b.key&&g.sG(a.player.T()))LKa(a);else{var c;(c=!g.U(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.Lr||!a.kp);(c?0:g.sG(a.player.T())||g.wG(a.player.T()))&&MKa(a)}a.Xk=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.U(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Na(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ga,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=SHa(c))&&(d.locationInfo=c);c=d}Q6("Connecting to: "+g.yj(b));"cast-selector-receiver"==b.key?(S6(c||null),c=c||null,
l6()?i6().setLaunchParams(c):g6("setLaunchParams called before ready.")):!c&&b7()&&P6()==b.key?r4("yt-remote-connection-change",!0):(Z6(),S6(c||null),c=O6().Kg(),(c=z4(c,b.key))&&$6(c,1))}},MKa=function(a){a.player.Wa().Nb()?a.player.pauseVideo():(a.An=function(b){KKa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.An));
a.kp&&a.kp.Ec();W6()||(d7=!0)},LKa=function(a){a.player.Wa().Nb()?a.player.pauseVideo():(a.An=function(b){KKa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.An));
a.Vo&&a.Vo.Ec();W6()||(d7=!0)},HIa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},$4={"'":"\\'"},NKa={},aIa={WR:"atp",l1:"ska",g0:"que",yZ:"mus",k1:"sus",PV:"dsp",z0:"seq",cZ:"mic",PU:"dpa",jS:"cds"},F4,B4="",uIa=pIa("loadCastFramework")||pIa("loadCastApplicationFramework"),wIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(K4,g.E);g.k=K4.prototype;g.k.ng=function(a){this.B=arguments;this.i=!1;this.gb?this.u=g.Ta()+this.Jf:this.gb=g.Bm(this.C,this.Jf)};
g.k.stop=function(){this.gb&&(g.A.clearTimeout(this.gb),this.gb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.da=function(){this.stop();K4.Fd.da.call(this)};
g.k.NJ=function(){this.u?(this.gb=g.Bm(this.C,this.u-g.Ta()),this.u=null):(this.gb=null,this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B)))};g.u(L4,g.E);g.k=L4.prototype;g.k.ng=function(a){this.u=arguments;this.gb||this.l?this.i=!0:M4(this)};
g.k.stop=function(){this.gb&&(g.A.clearTimeout(this.gb),this.gb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.gb||(this.i=!1,M4(this))};
g.k.da=function(){g.E.prototype.da.call(this);this.stop()};O4.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
O4.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var Q4=new g.Rl;g.u(yIa,g.xl);S4.prototype.i=null;S4.prototype.getOptions=function(){var a;(a=this.i)||(a={},AIa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var p7;g.Ua(zIa,S4);p7=new zIa;g.k=T4.prototype;g.k.im=null;g.k.zi=!1;g.k.Gp=null;g.k.NA=null;g.k.mp=null;g.k.Ap=null;g.k.Rk=null;g.k.Pl=null;g.k.Bn=null;g.k.De=null;g.k.Es=0;g.k.Di=null;g.k.Fv=null;g.k.Lk=null;g.k.bq=-1;g.k.QG=!0;g.k.Lm=!1;g.k.xw=0;g.k.Ru=null;var FIa={},W4={};g.k=T4.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.ZP=function(a){a=a.target;var b=this.Ru;b&&3==e5(a)?b.ng():this.LH(a)};
g.k.LH=function(a){try{if(a==this.De)a:{var b=e5(this.De),c=this.De.I,d=this.De.getStatus();if(g.Be&&!g.de(10)||g.De&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.kg&&!g5(this.De))break a;this.Lm||4!=b||7==c||(8==c||0>=d?this.i.gi(3):this.i.gi(2));a5(this);var e=this.De.getStatus();this.bq=e;var f=g5(this.De);(this.zi=200==e)?(4==b&&Y4(this),this.I?(GIa(this,b,f),g.kg&&this.zi&&3==b&&(this.B.ya(this.u,"tick",this.SP),this.u.start())):X4(this,f),this.zi&&!this.Lm&&(4==b?this.i.Ts(this):(this.zi=
!1,V4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Lk=3,R4(13)):(this.Lk=0,R4(14)),Y4(this),Z4(this))}}catch(h){this.De&&g5(this.De)}finally{}};
g.k.SP=function(){var a=e5(this.De),b=g5(this.De);this.Es<b.length&&(a5(this),GIa(this,a,b),this.zi&&4!=a&&V4(this))};
g.k.vP=function(a){P4((0,g.C)(this.uP,this,a),0)};
g.k.uP=function(a){this.Lm||(a5(this),X4(this,a),V4(this))};
g.k.bG=function(a){P4((0,g.C)(this.tP,this,a),0)};
g.k.tP=function(a){this.Lm||(Y4(this),this.zi=a,this.i.Ts(this),this.i.gi(4))};
g.k.cancel=function(){this.Lm=!0;Y4(this)};
g.k.DP=function(){this.Gp=null;var a=Date.now();0<=a-this.NA?(2!=this.Ap&&this.i.gi(3),Y4(this),this.Lk=2,R4(18),Z4(this)):JIa(this,this.NA-a)};
g.k.getLastError=function(){return this.Lk};g.Ua(c5,g.Rl);var QIa=/^https?$/i,OKa=["POST","PUT"];g.k=c5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.W+"; newUri="+a);b=b?b.toUpperCase():"GET";this.W=a;this.u="";this.I=0;this.za=b;this.ga=!1;this.B=!0;this.i=this.ea?BIa(this.ea):BIa(p7);this.ca=this.ea?this.ea.getOptions():p7.getOptions();this.i.onreadystatechange=(0,g.C)(this.PF,this);try{q4(f5(this,"Opening Xhr")),this.la=!0,this.i.open(b,String(a),!0),this.la=!1}catch(f){q4(f5(this,"Error opening Xhr: "+f.message));PIa(this,f);return}a=
c||"";var e=this.headers.clone();d&&XHa(d,function(f,h){e.set(h,f)});
d=g.cb(e.rh(),NIa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(OKa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Da&&(this.i.responseType=this.Da);"withCredentials"in this.i&&this.i.withCredentials!==this.ia&&(this.i.withCredentials=this.ia);try{SIa(this),0<this.J&&(this.Y=MIa(this.i),q4(f5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.JB,this)):this.X=g.Bm(this.JB,this.J,this)),q4(f5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){q4(f5(this,"Send error: "+f.message)),PIa(this,f)}};
g.k.JB=function(){"undefined"!=typeof g.H_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.I=8,f5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(f5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),d5(this))};
g.k.da=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),d5(this,!0));c5.Fd.da.call(this)};
g.k.PF=function(){this.na()||(this.la||this.L||this.C?RIa(this):this.CO())};
g.k.CO=function(){RIa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==e5(this)};
g.k.getStatus=function(){try{return 2<e5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=TIa.prototype;g.k.yw=null;g.k.Bg=null;g.k.Su=!1;g.k.bH=null;g.k.zt=null;g.k.Sy=null;g.k.zw=null;g.k.Ma=null;g.k.Kj=-1;g.k.cq=null;g.k.mq=null;g.k.connect=function(a){this.zw=a;a=h5(this.i,null,this.zw);R4(3);this.bH=Date.now();var b=this.i.J;null!=b?(this.cq=b[0],(this.mq=b[1])?(this.Ma=1,UIa(this)):(this.Ma=2,j5(this))):(o4(a,"MODE","init"),this.Bg=new T4(this,void 0,void 0,void 0),this.Bg.im=this.yw,U4(this.Bg,a,!1,null,!0),this.Ma=0)};
g.k.DK=function(a){if(a)this.Ma=2,j5(this);else{R4(4);var b=this.i;b.Ki=b.Vk.Kj;q5(b,9)}a&&this.gi(2)};
g.k.Ax=function(a){return this.i.Ax(a)};
g.k.abort=function(){this.Bg&&(this.Bg.cancel(),this.Bg=null);this.Kj=-1};
g.k.KB=function(){return!1};
g.k.SF=function(a,b){this.Kj=a.bq;if(0==this.Ma)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Ki=this.Kj;q5(c,2);return}this.cq=c[0];this.mq=c[1]}else c=this.i,c.Ki=this.Kj,q5(c,2);else if(2==this.Ma)if(this.Su)R4(7),this.Sy=Date.now();else if("11111"==b){if(R4(6),this.Su=!0,this.zt=Date.now(),c=this.zt-this.bH,!g.Be||g.de(10)||500>c)this.Kj=200,this.Bg.cancel(),R4(12),i5(this.i,this,!0)}else R4(8),this.zt=this.Sy=Date.now(),this.Su=!1};
g.k.Ts=function(){this.Kj=this.Bg.bq;if(this.Bg.zi)0==this.Ma?this.mq?(this.Ma=1,UIa(this)):(this.Ma=2,j5(this)):2==this.Ma&&((!g.Be||g.de(10)?!this.Su:200>this.Sy-this.zt)?(R4(11),i5(this.i,this,!1)):(R4(12),i5(this.i,this,!0)));else{0==this.Ma?R4(9):2==this.Ma&&R4(10);var a=this.i;this.Bg.getLastError();a.Ki=this.Kj;q5(a,2)}};
g.k.ds=function(){return this.i.ds()};
g.k.isActive=function(){return this.i.isActive()};
g.k.gi=function(a){this.i.gi(a)};g.k=k5.prototype;g.k.Ji=null;g.k.Fq=null;g.k.og=null;g.k.Xd=null;g.k.Aw=null;g.k.At=null;g.k.yC=null;g.k.Us=null;g.k.yr=0;g.k.tM=0;g.k.Bf=null;g.k.il=null;g.k.Oj=null;g.k.Um=null;g.k.Vk=null;g.k.Dv=null;g.k.Qo=-1;g.k.wE=-1;g.k.Ki=-1;g.k.wo=0;g.k.fo=0;g.k.Mm=8;g.Ua(WIa,g.xl);g.Ua(XIa,g.xl);g.k=k5.prototype;g.k.connect=function(a,b,c,d,e){R4(0);this.Aw=b;this.Fq=c||{};d&&void 0!==e&&(this.Fq.OSID=d,this.Fq.OAID=e);this.C?(P4((0,g.C)(this.QC,this,a),100),aJa(this)):this.QC(a)};
g.k.QC=function(a){this.Vk=new TIa(this);this.Vk.yw=this.Ji;this.Vk.l=this.B;this.Vk.connect(a)};
g.k.KB=function(){return 0==this.Ma};
g.k.getState=function(){return this.Ma};
g.k.ZF=function(a){this.il=null;eJa(this,a)};
g.k.YF=function(){this.Oj=null;this.Xd=new T4(this,this.l,"rpc",this.I);this.Xd.im=this.Ji;this.Xd.xw=0;var a=this.yC.clone();m4(a,"RID","rpc");m4(a,"SID",this.l);m4(a,"CI",this.Dv?"0":"1");m4(a,"AID",this.Qo);l5(this,a);if(!g.Be||g.de(10))m4(a,"TYPE","xmlhttp"),U4(this.Xd,a,!0,this.Us,!1);else{m4(a,"TYPE","html");var b=this.Xd,c=!!this.Us;b.Ap=3;b.Rk=n4(a.clone());IIa(b,c)}};
g.k.SF=function(a,b){if(0!=this.Ma&&(this.Xd==a||this.og==a))if(this.Ki=a.bq,this.og==a&&3==this.Ma)if(7<this.Mm){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Oj){if(this.Xd)if(this.Xd.mp+3E3<this.og.mp)n5(this),this.Xd.cancel(),this.Xd=null;else break a;p5(this);R4(19)}}else this.wE=c[1],0<this.wE-this.Qo&&37500>c[2]&&this.Dv&&0==this.fo&&!this.Um&&(this.Um=P4((0,g.C)(this.XM,this),6E3));else q5(this,11)}else b!=NKa.DU.i&&q5(this,11);else if(this.Xd==
a&&n5(this),!g.rc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Qo=e[0];e=e[1];2==this.Ma?"c"==e[0]?(this.l=e[1],this.Us=e[2],e=e[3],null!=e?this.Mm=e:this.Mm=6,this.Ma=3,this.Bf&&this.Bf.MC(),this.yC=h5(this,this.ds()?this.Us:null,this.Aw),fJa(this)):"stop"==e[0]&&q5(this,7):3==this.Ma&&("stop"==e[0]?q5(this,7):"noop"!=e[0]&&this.Bf&&this.Bf.LC(e),this.fo=0)}}};
g.k.XM=function(){null!=this.Um&&(this.Um=null,this.Xd.cancel(),this.Xd=null,p5(this),R4(20))};
g.k.Ts=function(a){if(this.Xd==a){n5(this);this.Xd=null;var b=2}else if(this.og==a)this.og=null,b=1;else return;this.Ki=a.bq;if(0!=this.Ma)if(a.zi)1==b?(b=Q4,b.dispatchEvent(new WIa(b,a.Bn?a.Bn.length:0,Date.now()-a.mp,this.wo)),m5(this),this.u.length=0):fJa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ki)){if(d=1==b)this.og||this.il||1==this.Ma||2<=this.wo?d=!1:(this.il=P4((0,g.C)(this.ZF,this,a),gJa(this,this.wo)),this.wo++,d=!0);d=!(d||2==b&&p5(this))}if(d)switch(c){case 1:q5(this,
5);break;case 4:q5(this,10);break;case 3:q5(this,6);break;case 7:q5(this,12);break;default:q5(this,2)}}};
g.k.XK=function(a){if(!g.fb(arguments,this.Ma))throw Error("Unexpected channel state: "+this.Ma);};
g.k.GQ=function(a){a?R4(2):(R4(1),hJa(this,8))};
g.k.Ax=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new c5;a.ia=!1;return a};
g.k.isActive=function(){return!!this.Bf&&this.Bf.isActive(this)};
g.k.gi=function(a){var b=Q4;b.dispatchEvent(new XIa(b,a))};
g.k.ds=function(){return!(!g.Be||g.de(10))};
g.k=iJa.prototype;g.k.MC=function(){};
g.k.LC=function(){};
g.k.KC=function(){};
g.k.jx=function(){};
g.k.vD=function(){return{}};
g.k.isActive=function(){return!0};g.k=jJa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.MCa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.rg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ua(r5,g.E);g.k=r5.prototype;g.k.nP=function(){this.Jf=Math.min(3E5,2*this.Jf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Jf+15E3*Math.random();g.$m(this.i,a);this.l=g.Ta()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Jf=5E3};g.Ua(s5,iJa);g.k=s5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Pf=function(a){return this.u.Pf(a)};
g.k.V=function(a,b){return this.u.V.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.zi(this.u),mJa(this),g.zi(this.l),this.l=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.W="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ca+"/test";b=this.ca+"/bind";var d=new k5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ea),e=this.i;e&&(e.Bf=null);d.Bf=this;this.i=d;t5(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Ji||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ji=f}e?(3!=e.getState()&&0==cJa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.Qo)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Yb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(c):u5(this)&&(t5(this),bJa(this.i,c))};
g.k.MC=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)bJa(this.i,a[b])}this.V("handlerOpened")};
g.k.KC=function(a){var b=2==a&&401==this.i.Ki;4==a||b||this.l.start();this.V("handlerError",a,b)};
g.k.jx=function(a){if(!this.l.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.vD=function(){var a={v:2};this.W&&(a.gsessionid=this.W);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Yb(a,this.C);return a};
g.k.LC=function(a){"S"==a[0]?this.W=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),$Ia(this.i)):this.V("handlerMessage",new kJa(a[0],a[1]))};
g.k.cv=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.ia&&this.i){var b=this.i.Ji||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ji=b}};
g.k.jQ=function(){this.l.isActive();0==cJa(this.i)&&this.connect(this.C,this.B)};v5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
v5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
v5.prototype.C=function(a){a(Error("request timed out"))};var tJa=Date.now(),y5=null,B5=Array(50),A5=-1,C5=!1;g.Ua(D5,g.R);D5.prototype.Kg=function(){return this.screens};
D5.prototype.contains=function(a){return!!y4(this.screens,a)};
D5.prototype.get=function(a){return a?z4(this.screens,a):null};
D5.prototype.info=function(a){z5(this.I,a)};g.u(E5,g.R);g.k=E5.prototype;g.k.start=function(){!this.i&&isNaN(this.gb)&&this.lG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.gb)||(g.so(this.gb),this.gb=NaN)};
g.k.da=function(){this.stop();g.R.prototype.da.call(this)};
g.k.lG=function(){this.gb=NaN;this.i=g.Pp(w5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.PJ,this),onError:(0,g.C)(this.OJ,this),onTimeout:(0,g.C)(this.QJ,this)})};
g.k.PJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.I;var d=-1;this.C&&c.shortLivedLoungeToken&&c.shortLivedLoungeToken.value&&c.shortLivedLoungeToken.refreshIntervalMs&&(c.screenIdType="shortLived",c.loungeToken=c.shortLivedLoungeToken.value,d=c.shortLivedLoungeToken.refreshIntervalMs);this.V("pairingComplete",new t4(c),d)};
g.k.OJ=function(a){this.i=null;a.status&&404==a.status?this.l>=PKa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=PKa[this.l],this.gb=g.qo((0,g.C)(this.lG,this),a),this.l++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.QJ=function(){this.i=null;this.V("pairingFailed",Error("Server not responding"))};
var PKa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(G5,D5);g.k=G5.prototype;g.k.start=function(){F5(this)&&this.V("screenChange");!g.Hu("yt-remote-lounge-token-expiration")&&xJa(this);g.so(this.i);this.i=g.qo((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){F5(this);uJa(this,a);H5(this,!1);this.V("screenChange");b(a);a.token||xJa(this)};
g.k.remove=function(a,b){var c=F5(this);wJa(this,a)&&(H5(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Bv=function(a,b,c,d){var e=F5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,H5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.da=function(){g.so(this.i);G5.Fd.da.call(this)};
g.k.wL=function(a){F5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}H5(this,!b);b&&z5(this.I,"Missed "+b+" lounge tokens.")};
g.k.vL=function(a){z5(this.I,"Requesting lounge tokens failed: "+a)};g.u(J5,g.R);g.k=J5.prototype;g.k.start=function(){var a=parseInt(g.Hu("yt-remote-fast-check-period")||"0",10);(this.B=g.Ta()-144E5<a?0:a)?M5(this):(this.B=g.Ta()+3E5,g.Gu("yt-remote-fast-check-period",this.B),this.Nz())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){I5("Updating availability on schedule.");var a=this.I(),b=g.Db(this.i,function(c,d){return c&&!!z4(a,d)},this);
L5(this,b)};
g.k.da=function(){g.so(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.R.prototype.da.call(this)};
g.k.Nz=function(){g.so(this.u);this.u=NaN;this.l&&this.l.abort();var a=zJa(this);if(p4(a)){var b=w5(this.C,"/pairing/get_screen_availability");this.l=x5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.C)(this.WO,this,a),(0,g.C)(this.VO,this))}else L5(this,{}),M5(this)};
g.k.WO=function(a,b){this.l=null;var c=g.Kb(zJa(this));if(g.yb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;L5(this,d);M5(this)}else this.Gd("Changing Screen set during request."),this.Nz()};
g.k.VO=function(a){this.Gd("Screen availability failed: "+a);this.l=null;M5(this)};
g.k.Gd=function(a){z5("OnlineScreenService",a)};g.Ua(N5,D5);g.k=N5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.V("screenChange"),this.i.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Bv=function(a,b,c,d){this.l.contains(a)?this.l.Bv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,z5(this.I,a),d(Error(a)))};
g.k.Kg=function(a){return a?this.screens:g.nb(this.screens,g.Ne(this.u,function(b){return!this.contains(b)},this))};
g.k.LB=function(){return g.Ne(this.Kg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.MB=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new E5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.zi(l);e(O5(h,m),n)});
l.subscribe("pairingFailed",function(m){g.zi(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.RJ=function(a,b,c,d){g.Pp(w5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){var h=new t4(f.screen||{});if(!h.name||DJa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);DJa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(O5(this,h))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.da=function(){g.zi(this.l);g.zi(this.i);N5.Fd.da.call(this)};
g.k.CL=function(){FJa(this);this.V("screenChange");this.i.update()};
N5.prototype.dispose=N5.prototype.dispose;g.Ua(Q5,g.R);g.k=Q5.prototype;g.k.getScreen=function(){return this.B};
g.k.cg=function(a){this.na()||(a&&S5(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.k.info=function(a){z5(this.ia,a)};
g.k.NB=function(){return null};
g.k.Yz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){S5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.da=function(){this.Yz("");Q5.Fd.da.call(this)};g.u(T5,Q5);g.k=T5.prototype;g.k.Xz=function(a){if(this.l){if(this.l==a)return;S5(this,"Overriding cast session with new session object");OJa(this);this.ca=!1;this.W="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea);KJa(this,"getMdxSessionStatus")};
g.k.Ro=function(a){this.info("launchWithParams no-op for Cast: "+g.yj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.cg()},this),(0,g.C)(function(){this.cg(Error("Failed to stop receiver app."))},this)):this.cg(Error("Stopping cast device without session."))};
g.k.Yz=function(){};
g.k.da=function(){this.info("disposeInternal");OJa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea));this.l=null;Q5.prototype.da.call(this)};
g.k.HP=function(a,b){if(!this.na())if(b){var c=N4(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yj(c));switch(d){case "mdxSessionStatus":IJa(this,c);break;case "loungeToken":LJa(this,c);break;default:S5(this,"Unknown youtube message: "+d)}}else S5(this,"Unable to parse message.")}else S5(this,"No data in message.")};
g.k.KD=function(a,b,c,d){g.so(this.L);this.L=0;CJa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(S5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.qo((0,g.C)(this.KD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.NB=function(){return this.l};
g.k.SJ=function(a){this.na()||a||(S5(this,"Cast session died."),this.cg())};g.u(W5,Q5);g.k=W5.prototype;g.k.Xz=function(a){this.l=a;this.l.addUpdateListener(this.ga)};
g.k.Ro=function(a){this.la=a;this.X()};
g.k.stop=function(){VJa(this);this.l?this.l.stop((0,g.C)(this.cg,this,null),(0,g.C)(this.cg,this,"Failed to stop DIAL device.")):this.cg()};
g.k.da=function(){VJa(this);this.l&&this.l.removeUpdateListener(this.ga);this.l=null;Q5.prototype.da.call(this)};
g.k.TJ=function(a){this.na()||a||(S5(this,"DIAL session died."),this.C(),this.C=g.Ka,this.cg())};g.u($5,Q5);$5.prototype.stop=function(){this.cg()};
$5.prototype.Xz=function(){};
$5.prototype.Ro=function(){g.so(this.l);this.l=NaN;var a=z4(this.u.Kg(),this.i.label);a?R5(this,a):this.cg(Error("No such screen"))};
$5.prototype.da=function(){g.so(this.l);this.l=NaN;Q5.prototype.da.call(this)};g.u(a6,g.R);g.k=a6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.W||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.C)(this.GO,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.UF,this),f,d,e);c.customDialLaunchCallback=(0,g.C)(this.sN,this);chrome.cast.initialize(c,(0,g.C)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.I),qJa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.OB,this)),this.u=XJa(this),chrome.cast.setCustomReceivers(this.u,g.Ka,(0,g.C)(function(h){this.Gd("Failed to set initial custom receivers: "+g.yj(h))},this)),this.V("yt-remote-cast2-availability-change",c6(this)),b(!0))},this),(0,g.C)(function(h){this.Gd("Failed to initialize API: "+g.yj(h));
b(!1)},this))};
g.k.pQ=function(a,b){b6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)b6("Unsetting old screen status: "+this.i.i.friendlyName),d6(this,null)}if(a&&b){if(!this.i){c=z4(this.l.Kg(),a);if(!c){b6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){b6("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=WJa(this,c);d||(b6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ka,(0,g.C)(function(e){this.Gd("Failed to set initial custom receivers: "+g.yj(e))},this)));
b6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);d6(this,new $5(this.l,d),!0)}this.i.Yz(b)}else b6("setConnectedScreenStatus: no screen.")};
g.k.qQ=function(a){this.na()?this.Gd("Setting connection data on disposed cast v2"):this.i?this.i.Ro(a):this.Gd("Setting connection data without a session")};
g.k.VJ=function(){this.na()?this.Gd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),d6(this,null)):b6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.UF,this),(0,g.C)(this.ZO,this))};
g.k.da=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.OB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.I);var a=nJa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.zi(this.i);g.R.prototype.da.call(this)};
g.k.Gd=function(a){z5("Controller",a)};
g.k.WF=function(a,b){this.i==a&&(b||d6(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.DO=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),b6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)b6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{b6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.V("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:d6(this,
new $5(this.l,a));break;case chrome.cast.ReceiverType.DIAL:d6(this,new W5(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:d6(this,new T5(this.l,a,this.B));break;default:this.Gd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Gd("Stopping receiver w/o session: "+a.friendlyName)}else this.Gd("onReceiverAction_ called without receiver.")};
g.k.sN=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Gd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return b6("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);d6(this,new W5(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,X5(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=SJa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.no(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=TJa(b,c)):a=TJa(b,c)):a=Z5(b);return a};
g.k.UF=function(a){if(!this.na()){b6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)b6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),d6(this,new T5(this.l,b,this.B),!0);else{this.Gd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=z4(this.l.Kg(),c.label);d&&u4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(b6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.zi(this.i),this.i=new T5(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.WF,this,this.i)),this.i.Ro(null));this.i.Xz(a)}}};
g.k.UJ=function(){return this.i?this.i.NB():null};
g.k.ZO=function(a){this.na()||(this.Gd("Failed to estabilish a session: "+g.yj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&d6(this,null))};
g.k.GO=function(a){b6("Receiver availability updated: "+a);if(!this.na()){var b=c6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;c6(this)!=b&&this.V("yt-remote-cast2-availability-change",c6(this))}};
g.k.OB=function(){this.na()||(this.u=XJa(this),b6("Updating custom receivers: "+g.yj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ka,(0,g.C)(function(){this.Gd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",c6(this)))};
a6.prototype.setLaunchParams=a6.prototype.qQ;a6.prototype.setConnectedScreenStatus=a6.prototype.pQ;a6.prototype.stopSession=a6.prototype.VJ;a6.prototype.getCastSession=a6.prototype.UJ;a6.prototype.requestSession=a6.prototype.requestSession;a6.prototype.init=a6.prototype.init;a6.prototype.dispose=a6.prototype.dispose;var j6=[];g.k=o6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";p6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.aj=a.hasPrevious,this.hasNext=a.hasNext,this.L=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.I=a.duration,this.W=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Nb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.I+q6(this):this.I};
g.k.clone=function(){return new o6(u6(this))};g.u(w6,g.R);g.k=w6.prototype;g.k.getState=function(){return this.Ma};
g.k.play=function(){y6(this)?(this.i?this.i.play(null,g.Ka,D6(this,"play")):C6(this,"play"),B6(this,1,s6(x6(this))),this.V("remotePlayerChange")):z6(this,this.play)};
g.k.pause=function(){y6(this)?(this.i?this.i.pause(null,g.Ka,D6(this,"pause")):C6(this,"pause"),B6(this,2,s6(x6(this))),this.V("remotePlayerChange")):z6(this,this.pause)};
g.k.seekTo=function(a){if(y6(this)){if(this.i){var b=x6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Nb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ka,D6(this,"seekTo",{newTime:a}))}else C6(this,"seekTo",{newTime:a});B6(this,3,a);this.V("remotePlayerChange")}else z6(this,g.Ra(this.seekTo,a))};
g.k.stop=function(){if(y6(this)){this.i?this.i.stop(null,g.Ka,D6(this,"stopVideo")):C6(this,"stopVideo");var a=x6(this);a.index=-1;a.videoId="";p6(a);A6(this,a);this.V("remotePlayerChange")}else z6(this,this.stop)};
g.k.setVolume=function(a,b){if(y6(this)){var c=x6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){z5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Gd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){z5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Gd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);C6(this,"setVolume",e)}c.muted=b;c.volume=a;A6(this,c)}else z6(this,g.Ra(this.setVolume,a,b))};
g.k.PB=function(a,b){if(y6(this)){var c=x6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.yj(b.style),g.Yb(d,c.i));C6(this,"setSubtitlesTrack",d);A6(this,c)}else z6(this,g.Ra(this.PB,a,b))};
g.k.setAudioTrack=function(a,b){if(y6(this)){var c=b.getLanguageInfo().getId();C6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=x6(this);d.audioTrackId=c;A6(this,d)}else z6(this,g.Ra(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=x6(this);c=c||0;var m={videoId:a,currentIndex:c};t6(l,a,c);void 0!==b&&(r6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.yj(h));C6(this,"setPlaylist",m);d||A6(this,l)};
g.k.Nu=function(a,b){if(y6(this)){if(a&&b){var c=x6(this);t6(c,a,b);A6(this,c)}C6(this,"previous")}else z6(this,g.Ra(this.Nu,a,b))};
g.k.nextVideo=function(a,b){if(y6(this)){if(a&&b){var c=x6(this);t6(c,a,b);A6(this,c)}C6(this,"next")}else z6(this,g.Ra(this.nextVideo,a,b))};
g.k.eD=function(){y6(this)?C6(this,"dismissAutoplay"):z6(this,this.eD)};
g.k.dispose=function(){if(3!=this.Ma){var a=this.Ma;this.Ma=3;this.V("proxyStateChange",a,this.Ma)}g.R.prototype.dispose.call(this)};
g.k.da=function(){iKa(this);this.u=null;this.B.clear();v6(this,null);g.R.prototype.da.call(this)};
g.k.bA=function(a){if((a!=this.Ma||2==a)&&3!=this.Ma&&0!=a){var b=this.Ma;this.Ma=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.AO=function(a,b){this.V(a,b)};
g.k.eN=function(a){if(!a)this.Cr(null),v6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=x6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)z5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,A6(this,b)}};
g.k.Cr=function(a){z5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),jKa(this),this.V("remotePlayerChange")};
g.k.dN=function(a){a?(jKa(this),this.V("remotePlayerChange")):this.Cr(null)};
g.k.sA=function(){C6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.lN=function(){var a=fKa();a&&v6(this,a)};
g.k.Gd=function(a){z5("CP",a)};g.u(E6,g.R);g.k=E6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Hb.listId=c);this.Hb.videoId=d;this.Hb.index=h||0;this.Hb.state=3;r6(this.Hb,m);this.B="UNSUPPORTED";F6("Connecting with setPlaylist and params: "+g.yj(l));this.i.connect({method:"setPlaylist",
params:g.yj(l)},a,iIa())}else F6("Connecting without params"),this.i.connect({},a,iIa());lKa(this)};
g.k.cv=function(a){this.i.cv(a)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),G6(this,3));g.R.prototype.dispose.call(this)};
g.k.da=function(){H6(this);J6(this);I6(this);g.so(this.J);this.J=NaN;g.so(this.L);this.L=NaN;this.u=null;g.To(this.W);this.W.length=0;this.i.dispose();g.R.prototype.da.call(this);this.B=this.I=this.l=this.Hb=this.i=null};
g.k.qL=function(){this.qo(2)};
g.k.iN=function(){F6("Channel opened");this.ca&&(this.ca=!1,I6(this),this.Y=g.qo((0,g.C)(function(){F6("Timing out waiting for a screen.");this.qo(1)},this),15E3));
mIa(lJa(this.i),this.ga)};
g.k.fN=function(){F6("Channel closed");isNaN(this.C)?E4(!0):E4();this.dispose()};
g.k.gN=function(a,b){E4();isNaN(this.Vq())?(b&&"shortLived"==this.ea&&this.V("browserChannelAuthError",a),F6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ca=!0,F6("Channel error: "+a+" with reconnection in "+this.Vq()+" ms"),G6(this,2))};
g.k.hN=function(a){a.params?F6("Received: action="+a.action+", params="+g.yj(a.params)):F6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=N4(a.params.devices);this.l=g.Qc(a,function(c){return new s4(c)});
a=!!g.cb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
oKa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
oKa(this,!1);break;case "remoteConnected":var b=new s4(N4(a.params.device));g.cb(this.l,function(c){return b?c.id==b.id:!1})||THa(this.l,b);
break;case "remoteDisconnected":b=new s4(N4(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":qKa(this,a);break;case "nowPlaying":sKa(this,a);break;case "onStateChange":rKa(this,a);break;case "onAdStateChange":tKa(this,a);break;case "onVolumeChanged":uKa(this,a);break;case "onSubtitlesTrackChanged":pKa(this,a);break;case "nowAutoplaying":vKa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.V("autoplayModeChange",this.B);"DISABLED"==this.B&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":wKa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:F6("Unrecognized action: "+a.action)}};
g.k.fQ=function(){if(this.u){var a=this.u;this.u=null;this.Hb.videoId!=a&&K6(this,"getNowPlaying")}};
g.k.mL=function(){var a=3;this.na()||(a=0,isNaN(this.Vq())?u5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.qo=function(a){F6("Disconnecting with "+a);H6(this);this.V("beforeDisconnect",a);1==a&&E4();mJa(this.i,a);this.dispose()};
g.k.kL=function(){var a=this.Hb;this.u&&(a=this.Hb.clone(),t6(a,this.u,a.index));return u6(a)};
g.k.rQ=function(a){var b=new o6(a);b.videoId&&b.videoId!=this.Hb.videoId&&(this.u=b.videoId,g.so(this.J),this.J=g.qo((0,g.C)(this.fQ,this),5E3));var c=[];this.Hb.listId==b.listId&&this.Hb.videoId==b.videoId&&this.Hb.index==b.index||c.push("remoteQueueChange");this.Hb.playerState==b.playerState&&this.Hb.volume==b.volume&&this.Hb.muted==b.muted&&s6(this.Hb)==s6(b)&&g.yj(this.Hb.i)==g.yj(b.i)||c.push("remotePlayerChange");this.Hb.reset(a);g.Ab(c,function(d){this.V(d)},this)};
g.k.JD=function(){var a=this.i.I.id,b=g.cb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Vq=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Ta():NaN};
g.k.hL=function(){return this.B||"UNSUPPORTED"};
g.k.iL=function(){return this.I||""};
g.k.WJ=function(){if(!isNaN(this.Vq())){var a=this.i.l;a.i.ng();a.start()}};
g.k.oQ=function(a,b){K6(this,a,b);nKa(this)};
g.k.QB=function(){var a=g.Lq("SID","")||"",b=g.Lq("SAPISID","")||"",c=g.Lq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
E6.prototype.subscribe=E6.prototype.subscribe;E6.prototype.unsubscribeByKey=E6.prototype.Pf;E6.prototype.getProxyState=E6.prototype.mL;E6.prototype.disconnect=E6.prototype.qo;E6.prototype.getPlayerContextData=E6.prototype.kL;E6.prototype.setPlayerContextData=E6.prototype.rQ;E6.prototype.getOtherConnectedRemoteId=E6.prototype.JD;E6.prototype.getReconnectTimeout=E6.prototype.Vq;E6.prototype.getAutoplayMode=E6.prototype.hL;E6.prototype.getAutoplayVideoId=E6.prototype.iL;E6.prototype.reconnect=E6.prototype.WJ;
E6.prototype.sendMessage=E6.prototype.oQ;E6.prototype.getXsrfToken=E6.prototype.QB;g.u(L6,D5);g.k=L6.prototype;g.k.Kg=function(a){return this.If.$_gs(a)};
g.k.contains=function(a){return!!this.If.$_c(a)};
g.k.get=function(a){return this.If.$_g(a)};
g.k.start=function(){this.If.$_st()};
g.k.add=function(a,b,c){this.If.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.If.$_r(a,b,c)};
g.k.Bv=function(a,b,c,d){this.If.$_un(a,b,c,d)};
g.k.da=function(){for(var a=0,b=this.i.length;a<b;++a)this.If.$_ubk(this.i[a]);this.i.length=0;this.If=null;D5.prototype.da.call(this)};
g.k.XJ=function(){this.V("screenChange")};
g.k.hO=function(){this.V("onlineScreenChange")};
N5.prototype.$_st=N5.prototype.start;N5.prototype.$_gspc=N5.prototype.RJ;N5.prototype.$_gsppc=N5.prototype.MB;N5.prototype.$_c=N5.prototype.contains;N5.prototype.$_g=N5.prototype.get;N5.prototype.$_a=N5.prototype.add;N5.prototype.$_un=N5.prototype.Bv;N5.prototype.$_r=N5.prototype.remove;N5.prototype.$_gs=N5.prototype.Kg;N5.prototype.$_gos=N5.prototype.LB;N5.prototype.$_s=N5.prototype.subscribe;N5.prototype.$_ubk=N5.prototype.Pf;var Y6=null,d7=!1,M6=null,N6=null,c7=null,R6=[];g.u(e7,g.E);g.k=e7.prototype;g.k.da=function(){g.E.prototype.da.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.xb;a.unsubscribe("proxyStateChange",this.RF,this);a.unsubscribe("remotePlayerChange",this.Ir,this);a.unsubscribe("remoteQueueChange",this.Lu,this);a.unsubscribe("previousNextChange",this.OF,this);a.unsubscribe("nowAutoplaying",this.IF,this);a.unsubscribe("autoplayDismissed",this.gF,this);this.xb=this.l=null};
g.k.RB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.xb.Ma)if(f7(this)){if(!x6(this.xb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":x6(this.xb).Nb()?this.xb.pause():this.xb.play();break;case "control_play":this.xb.play();break;case "control_pause":this.xb.pause();break;case "control_seek":this.J.ng(c[0],c[1]);break;case "control_subtitles_set_track":g7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();h7(this,0===c?void 0:c);break;case "control_seek":h7(this,c[0]);break;case "control_subtitles_set_track":g7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.bN=function(a){this.L.ng(a)};
g.k.XQ=function(a){this.RB("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.fH=function(){var a=this.G.getOption("captions","track");g.Pb(a)||g7(this,a)};
g.k.Db=function(a){this.l.Db(a,this.G.getVideoData().lengthSeconds)};
g.k.QN=function(){g.Pb(this.B)||HKa(this,this.B);this.C=!1};
g.k.RF=function(a,b){this.u.stop();2===b&&this.aH()};
g.k.Ir=function(){if(f7(this)){this.i.stop();var a=x6(this.xb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Ne=1;break;case 1082:case 1083:this.l.Ne=0;break;default:this.l.Ne=-1}switch(a.playerState){case 1081:case 1:this.tb(new g.dK(8));this.ZG();break;case 1085:case 3:this.tb(new g.dK(9));break;case 1083:case 0:this.tb(new g.dK(2));this.J.stop();this.Db(this.G.getVideoData().lengthSeconds);break;case 1084:this.tb(new g.dK(4));break;case 2:this.tb(new g.dK(4));this.Db(s6(a));
break;case -1:this.tb(new g.dK(64));break;case -1E3:this.tb(new g.dK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=x6(this.xb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,HKa(this,a));a=x6(this.xb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.W.isActive()||this.CH()}else GKa(this)};
g.k.OF=function(){this.G.V("mdxpreviousnextchange")};
g.k.Lu=function(){f7(this)||GKa(this)};
g.k.IF=function(a){isNaN(a)||this.G.V("mdxnowautoplaying",a)};
g.k.gF=function(){this.G.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){f7(this)&&this.xb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===x6(this.xb).playerState?h7(this,a):b&&this.xb.seekTo(a)};
g.k.CH=function(){var a=this;if(f7(this)){var b=x6(this.xb);this.events.Ib(this.X);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.X=this.events.N(this.G,"onVolumeChange",function(c){FKa(a,c)})}};
g.k.ZG=function(){this.i.stop();if(!this.xb.na()){var a=x6(this.xb);a.Nb()&&this.tb(new g.dK(8));this.Db(s6(a));this.i.start()}};
g.k.aH=function(){this.u.stop();this.i.stop();var a=this.xb.u.getReconnectTimeout();2==this.xb.Ma&&!isNaN(a)&&this.u.start()};
g.k.tb=function(a){this.u.stop();var b=this.I;if(!g.iK(b,a)){var c=g.W(a,2);c!==g.W(this.I,2)&&this.G.Dn(c);this.I=a;JKa(this.l,b,a)}};g.u(i7,g.X);i7.prototype.Ec=function(){this.i.show()};
i7.prototype.jb=function(){this.i.hide()};
i7.prototype.l=function(){g.KJ("https://support.google.com/youtube/answer/7640706")};
i7.prototype.u=function(){r4("mdx-manual-pairing-popup-ok");this.jb()};g.u(j7,g.X);j7.prototype.Ec=function(){this.i.show()};
j7.prototype.jb=function(){this.i.hide()};
j7.prototype.l=function(){r4("mdx-privacy-popup-cancel");this.jb()};
j7.prototype.u=function(){r4("mdx-privacy-popup-confirm");this.jb()};g.u(k7,g.X);k7.prototype.l=function(a){IKa(this,a.state)};g.u(l7,g.SP);l7.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Ml=g.Bb(a,this.i,this),g.TP(this,g.Qc(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.bh(a),this.enable(!0)):this.enable(!1)};
l7.prototype.i=function(a){return a.key};
l7.prototype.Nh=function(a){return"cast-selector-receiver"===a?"Cast...":this.Ml[a].name};
l7.prototype.Xe=function(a){g.SP.prototype.Xe.call(this,a);this.G.setOption("remote","currentReceiver",this.Ml[a]);this.bb.jb()};g.u(m7,g.hN);g.k=m7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.XF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.U(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.U(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.U(a.experiments,"enable_cast_short_lived_lounge_token")};AKa(b,a);this.subscriptions.push(g.xo("yt-remote-before-disconnect",this.ZM,this));this.subscriptions.push(g.xo("yt-remote-connection-change",this.HO,this));this.subscriptions.push(g.xo("yt-remote-receiver-availability-change",
this.QF,this));this.subscriptions.push(g.xo("yt-remote-auto-connect",this.FO,this));this.subscriptions.push(g.xo("yt-remote-receiver-resumed",this.EO,this));this.subscriptions.push(g.xo("mdx-privacy-popup-confirm",this.VP,this));this.subscriptions.push(g.xo("mdx-privacy-popup-cancel",this.UP,this));this.subscriptions.push(g.xo("mdx-manual-pairing-popup-ok",this.iM,this));this.QF()};
g.k.load=function(){this.player.cancelPlayback();g.hN.prototype.load.call(this);this.lh=new e7(this,this.player,this.xb);var a=(a=EKa())?a.currentTime:0;var b=b7()?new w6(W6(),void 0):null;0==a&&b&&(a=s6(x6(b)));0!==a&&this.Db(a);JKa(this,this.Qc,this.Qc);this.player.xj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.Xk=this.ci;g.Ai(this.lh,this.xb);this.xb=this.lh=null;g.hN.prototype.unload.call(this);this.player.xj(5);n7(this)};
g.k.da=function(){g.yo(this.subscriptions);g.hN.prototype.da.call(this)};
g.k.rj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.lh.RB.apply(this.lh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Ne};
g.k.nL=function(){return this.loaded?this.lh.suggestion:null};
g.k.aj=function(){return this.xb?x6(this.xb).aj:!1};
g.k.hasNext=function(){return this.xb?x6(this.xb).hasNext:!1};
g.k.Db=function(a,b){this.xE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.xE};
g.k.getProgressState=function(){var a=x6(this.xb),b=this.player.getVideoData();return{allowSeeking:g.U(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Le():!a.isAdPlaying()&&this.player.Le(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+q6(a):a.B,isAtLiveHead:1>=(a.u?a.l+q6(a):a.l)-this.getCurrentTime(),loaded:a.W,seekableEnd:a.u?a.l+q6(a):a.l,seekableStart:0<a.C?a.C+
q6(a):a.C}};
g.k.nextVideo=function(){this.xb&&this.xb.nextVideo()};
g.k.Nu=function(){this.xb&&this.xb.Nu()};
g.k.ZM=function(a){1===a&&(this.Dz=this.xb?x6(this.xb):null)};
g.k.HO=function(){var a=b7()?new w6(W6(),void 0):null;if(a){var b=this.Xk;this.loaded&&this.unload();this.xb=a;this.Dz=null;b.key!==this.ci.key&&(this.Xk=b,this.load())}else g.zi(this.xb),this.xb=null,this.loaded&&(this.unload(),(a=this.Dz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,s6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.QF=function(){var a=[this.ci],b=a.concat,c=BKa();k6()&&g.Hu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Ml=b.call(a,c);a=X6()||this.ci;o7(this,a);this.player.xa("onMdxReceiversChange")};
g.k.FO=function(){var a=X6();o7(this,a)};
g.k.EO=function(){this.Xk=X6()};
g.k.VP=function(){this.Lr=!0;n7(this);d7=!1;Y6&&$6(Y6,1);Y6=null};
g.k.UP=function(){this.Lr=!1;n7(this);o7(this,this.ci);this.Xk=this.ci;d7=!1;Y6=null;this.player.playVideo()};
g.k.iM=function(){this.pu=!0;n7(this);g.Gu("yt-remote-manual-pairing-warning-shown",!0,2592E3);d7=!1;Y6&&$6(Y6,1);Y6=null};
g.k.He=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ml;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?m6():o7(this,b)),this.loaded?this.Xk:this.ci;case "quickCast":return 2===this.Ml.length&&"cast-selector-receiver"===this.Ml[1].key?(b&&m6(),!0):!1}};
g.k.sA=function(){this.xb.sA()};
g.k.xi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nN.remote=m7;})(_yt_player);
